server:
  port: 9090
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka
jaeger:
    service-name: API-GATEWAY
    sampler-type: const
    sampler-param: 1
    endpoint: http://localhost:14268/api/traces
spring:
  application:
    name: API-GATEWAY